### ISSUE TITLE
[FEATURE] Add proper percentage calculation logic 

### ISSUE THREAD

**Issue by Almaz-KG** [guibranco/progressbar#61]
### Description

The following URL must show 10%, because 4 of 40 is 10%, but it's showing 4%, which is not correct

> https://progress-bar.xyz/4/?scale=40&title=done

<img width="58" alt="Screenshot 2024-11-13 at 11 56 00" src="https://github.com/user-attachments/assets/62b22d2c-1365-4cb3-b940-24cfa16506e5">

**Comment by guibranco** [comment]
Hi @Almaz-KG, thanks for reporting this issue! 📝

I’ll start investigating to identify the root cause and come up with a fix. 🔍 While I work on this, feel free to join in the investigation if you have any additional context or thoughts on the issue. 👥 Your input is always appreciated! 

I’ll update you as soon as I have more information. 🚧

### 🔄 Next Steps:
- Investigating the bug 🕵️‍♂️
- Looking for potential fixes 🛠️

Thanks again for your help! 😊

**Comment by guibranco** [comment]
@Almaz-KG fixed!

**Comment by Almaz-KG** [comment]
Thank you very much @guibranco !
